-- Insert groups
INSERT INTO _group (name) VALUES ('GroupA');
INSERT INTO _group (name) VALUES ('GroupB');
INSERT INTO _group (name) VALUES ('GroupC');

-- Insert courses
INSERT INTO course (name, type) VALUES ('Course1', 'MAIN');
INSERT INTO course (name, type) VALUES ('Course2', 'SECONDARY');
INSERT INTO course (name, type) VALUES ('Course3', 'MAIN');
INSERT INTO course (name, type) VALUES ('Course4', 'SECONDARY');
INSERT INTO course (name, type) VALUES ('Course5', 'MAIN');
INSERT INTO course (name, type) VALUES ('Course6', 'SECONDARY');
INSERT INTO course (name, type) VALUES ('Course7', 'MAIN');
INSERT INTO course (name, type) VALUES ('Course8', 'SECONDARY');
INSERT INTO course (name, type) VALUES ('Course9', 'MAIN');
INSERT INTO course (name, type) VALUES ('Course10', 'SECONDARY');

-- Insert students
INSERT INTO student (name, age, group_id) VALUES ('Student1', 19, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student2', 20, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student3', 21, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student4', 22, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student5', 23, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student6', 24, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student7', 25, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student8', 18, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student9', 19, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student10', 20, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student11', 21, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student12', 22, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student13', 23, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student14', 24, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student15', 25, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student16', 18, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student17', 19, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student18', 20, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student19', 21, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student20', 22, 1);
INSERT INTO student (name, age, group_id) VALUES ('Student21', 23, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student22', 24, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student23', 25, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student24', 18, 2);
INSERT INTO student (name, age, group_id) VALUES ('Student25', 19, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student26', 20, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student27', 21, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student28', 22, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student29', 23, 3);
INSERT INTO student (name, age, group_id) VALUES ('Student30', 24, 3);

-- Insert teachers
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher1', 40, 1);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher2', 45, 1);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher3', 50, 1);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher4', 55, 2);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher5', 60, 2);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher6', 35, 2);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher7', 40, 3);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher8', 45, 3);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher9', 50, 3);
INSERT INTO teacher (name, age, group_id) VALUES ('Teacher10', 55, 3);

-- Insert student-course relationships
INSERT INTO student_course (student_id, course_id) VALUES (1, 1);
INSERT INTO student_course (student_id, course_id) VALUES (1, 2);
INSERT INTO student_course (student_id, course_id) VALUES (2, 3);
INSERT INTO student_course (student_id, course_id) VALUES (2, 4);
INSERT INTO student_course (student_id, course_id) VALUES (3, 5);
INSERT INTO student_course (student_id, course_id) VALUES (3, 6);
INSERT INTO student_course (student_id, course_id) VALUES (4, 7);
INSERT INTO student_course (student_id, course_id) VALUES (4, 8);
INSERT INTO student_course (student_id, course_id) VALUES (5, 9);
INSERT INTO student_course (student_id, course_id) VALUES (5, 10);
INSERT INTO student_course (student_id, course_id) VALUES (6, 1);
INSERT INTO student_course (student_id, course_id) VALUES (6, 2);
INSERT INTO student_course (student_id, course_id) VALUES (7, 3);
INSERT INTO student_course (student_id, course_id) VALUES (7, 4);
INSERT INTO student_course (student_id, course_id) VALUES (8, 5);
INSERT INTO student_course (student_id, course_id) VALUES (8, 6);
INSERT INTO student_course (student_id, course_id) VALUES (9, 7);
INSERT INTO student_course (student_id, course_id) VALUES (9, 8);
INSERT INTO student_course (student_id, course_id) VALUES (10, 9);
INSERT INTO student_course (student_id, course_id) VALUES (10, 10);
INSERT INTO student_course (student_id, course_id) VALUES (11, 1);
INSERT INTO student_course (student_id, course_id) VALUES (11, 2);
INSERT INTO student_course (student_id, course_id) VALUES (12, 3);
INSERT INTO student_course (student_id, course_id) VALUES (12, 4);
INSERT INTO student_course (student_id, course_id) VALUES (13, 5);
INSERT INTO student_course (student_id, course_id) VALUES (13, 6);
INSERT INTO student_course (student_id, course_id) VALUES (14, 7);
INSERT INTO student_course (student_id, course_id) VALUES (14, 8);
INSERT INTO student_course (student_id, course_id) VALUES (15, 9);
INSERT INTO student_course (student_id, course_id) VALUES (15, 10);
INSERT INTO student_course (student_id, course_id) VALUES (16, 1);
INSERT INTO student_course (student_id, course_id) VALUES (16, 2);
INSERT INTO student_course (student_id, course_id) VALUES (17, 3);
INSERT INTO student_course (student_id, course_id) VALUES (17, 4);
INSERT INTO student_course (student_id, course_id) VALUES (18, 5);
INSERT INTO student_course (student_id, course_id) VALUES (18, 6);
INSERT INTO student_course (student_id, course_id) VALUES (19, 7);
INSERT INTO student_course (student_id, course_id) VALUES (19, 8);
INSERT INTO student_course (student_id, course_id) VALUES (20, 9);
INSERT INTO student_course (student_id, course_id) VALUES (20, 10);
INSERT INTO student_course (student_id, course_id) VALUES (21, 1);
INSERT INTO student_course (student_id, course_id) VALUES (21, 2);
INSERT INTO student_course (student_id, course_id) VALUES (22, 3);
INSERT INTO student_course (student_id, course_id) VALUES (22, 4);
INSERT INTO student_course (student_id, course_id) VALUES (23, 5);
INSERT INTO student_course (student_id, course_id) VALUES (23, 6);
INSERT INTO student_course (student_id, course_id) VALUES (24, 7);
INSERT INTO student_course (student_id, course_id) VALUES (24, 8);
INSERT INTO student_course (student_id, course_id) VALUES (25, 9);
INSERT INTO student_course (student_id, course_id) VALUES (25, 10);
INSERT INTO student_course (student_id, course_id) VALUES (26, 1);
INSERT INTO student_course (student_id, course_id) VALUES (26, 2);
INSERT INTO student_course (student_id, course_id) VALUES (27, 3);
INSERT INTO student_course (student_id, course_id) VALUES (27, 4);
INSERT INTO student_course (student_id, course_id) VALUES (28, 5);
INSERT INTO student_course (student_id, course_id) VALUES (28, 6);
INSERT INTO student_course (student_id, course_id) VALUES (29, 7);
INSERT INTO student_course (student_id, course_id) VALUES (29, 8);
INSERT INTO student_course (student_id, course_id) VALUES (30, 9);
INSERT INTO student_course (student_id, course_id) VALUES (30, 10);

-- Insert teacher-course relationships
INSERT INTO teacher_course (teacher_id, course_id) VALUES (1, 1);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (1, 2);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (2, 3);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (2, 4);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (3, 5);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (3, 6);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (4, 7);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (4, 8);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (5, 9);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (5, 10);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (6, 1);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (6, 2);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (7, 3);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (7, 4);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (8, 5);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (8, 6);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (9, 7);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (9, 8);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (10, 9);
INSERT INTO teacher_course (teacher_id, course_id) VALUES (10, 10);
